- platform: mqtt
  name: front_door_relay
  state_topic: "fhem/front/door_relay"
  command_topic: "fhem/front/door_relay/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: front_door_switch
  state_topic: "fhem/front/door"
  command_topic: "fhem/front/door/set"
  payload_on: "on"
  payload_off: "off"
- platform: template
  switches:
    front_door:
      value_template: '{% if is_state("switch.front_door_relay", "on") %} on {% elif is_state("switch.front_door_relay", "off") %} off {% else %} off {% endif %}'
      icon_template: '{% if is_state("switch.front_door_relay", "on") %}mdi:lock-open{% else %}mdi:lock{% endif %}'
      turn_on:
        service: switch.turn_on
        entity_id: switch.front_door_switch
      turn_off:
        service: switch.turn_off
        entity_id: switch.front_door_switch
- platform: mqtt
  name: "Garage Door"
  icon: mdi:lock
  state_topic: "fhem/garage/door"
  command_topic: "fhem/garage/door/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Pool Cleaner"
  state_topic: "fhem/pool_cleaner/switch"
  command_topic: "fhem/pool_cleaner/switch/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Car Heater"
  state_topic: "fhem/car_heater/switch"
  command_topic: "fhem/car_heater/switch/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Sauna mode"
  state_topic: "fhem/ventilation/power"
  command_topic: "fhem/ventilation/power/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Fireplace mode"
  state_topic: "fhem/ventilation/pressure"
  command_topic: "fhem/ventilation/pressure/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Away mode"
  state_topic: "fhem/ventilation/away"
  command_topic: "fhem/ventilation/away/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Air Conditioning"
  state_topic: "fhem/ventilation/ac"
  command_topic: "fhem/ventilation/ac/set"
  payload_on: "on"
  payload_off: "off"
