- platform: yr
  name: Weather
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - windDirection
    - humidity
    - cloudiness
- platform: speedtest
  minute:
    - 0
    - 10
    - 20
    - 30
    - 40
    - 50
  monitored_conditions:
    - ping
    - download
    - upload

