- platform: mqtt
  name: "Terrace"
  state_topic: "fhem/terrace/light"
  command_topic: "fhem/terrace/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Backyard"
  state_topic: "fhem/backyard/light"
  command_topic: "fhem/backyard/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Pool"
  state_topic: "fhem/pool/light"
  command_topic: "fhem/pool/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Garden"
  state_topic: "fhem/garden/light"
  command_topic: "fhem/garden/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Shed"
  state_topic: "fhem/shed/light"
  command_topic: "fhem/shed/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Pine"
  state_topic: "fhem/pine/light"
  command_topic: "fhem/pine/light/set"
  payload_on: "on"
  payload_off: "off"
