- platform: mqtt
  name: "Entry"
  state_topic: "fhem/entry/light"
  command_topic: "fhem/entry/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Fireplace room"
  state_topic: "fhem/fireplace_room/light"
  command_topic: "fhem/fireplace_room/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Lobby"
  state_topic: "fhem/lobby/light"
  command_topic: "fhem/lobby/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Lobby closet"
  state_topic: "fhem/lobby_closet/light"
  command_topic: "fhem/lobby_closet/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Movie room"
  state_topic: "fhem/movie_room/light"
  command_topic: "fhem/movie_room/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Movie room ambient"
  state_topic: "fhem/movie_room_amb/light"
  command_topic: "fhem/movie_room_amb/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Office"
  state_topic: "fhem/office/light"
  command_topic: "fhem/office/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Staircase wall"
  state_topic: "fhem/staircase_wall/light"
  command_topic: "fhem/staircase_wall/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Storage"
  state_topic: "fhem/storage/light"
  command_topic: "fhem/storage/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Toilet downstairs"
  state_topic: "fhem/toilet_ds/light"
  command_topic: "fhem/toilet_ds/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Utility room"
  state_topic: "fhem/utility_room/light"
  command_topic: "fhem/utility_room/light/set"
  payload_on: "on"
  payload_off: "off"
