- platform: mqtt
  name: "Bedroom"
  state_topic: "fhem/bedroom/light"
  command_topic: "fhem/bedroom/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Living room"
  state_topic: "fhem/living_room/light"
  command_topic: "fhem/living_room/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Living room spot"
  state_topic: "fhem/living_room_spot/light"
  command_topic: "fhem/living_room_spot/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Clothes room Kaisa"
  state_topic: "fhem/clothes_room/light"
  command_topic: "fhem/clothes_room/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Clothes room Toni"
  state_topic: "fhem/clothes_room2/light"
  command_topic: "fhem/clothes_room2/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Dining room"
  state_topic: "fhem/dining_room/light"
  command_topic: "fhem/dining_room/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Hall"
  state_topic: "fhem/hall/light"
  command_topic: "fhem/hall/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Kitchen ambient"
  state_topic: "fhem/kitchen_ambient/light"
  command_topic: "fhem/kitchen_ambient/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Kitchen"
  state_topic: "fhem/kitchen/light"
  command_topic: "fhem/kitchen/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Peppis room"
  state_topic: "fhem/peppis_room/light"
  command_topic: "fhem/peppis_room/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Samis room"
  state_topic: "fhem/samis_room/light"
  command_topic: "fhem/samis_room/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Staircase roof"
  state_topic: "fhem/staircase_roof/light"
  command_topic: "fhem/staircase_roof/light/set"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Toilet"
  state_topic: "fhem/toilet/light"
  command_topic: "fhem/toilet/light/set"
  payload_on: "on"
  payload_off: "off"
